export const ActionTypes = {
    SET_QUESTIONS : "SET_QUESTIONS",
    SELECTED_QUESTION : "SELECTED_QUESTION",
    REMOVE_SELECTED_QUESTION : "REMOVE_SELECTED_QUESTION",
    QUESTIONS_ERROR : 'QUESTIONS_ERROR'
}
